### ISSUE TITLE
Send NFTs

### ISSUE THREAD

**Issue by maxcodefaster** [TanglePay/TanglePay-SDK#27]
Hi,
how would you send NFTs with the sdk? 
Thank you :)

**Comment by alexmengyuan** [comment]
Hi,
there is a demo link for SDK usage, https://tanglepay.github.io/TanglePay-SDK/
and within the page there is an example for sending shimmer NFT, 
the code snippet can be found within the source code of that demo page, 
https://github.com/TanglePay/TanglePay-SDK/blob/main/index.html
hope this solves your problem.
Thanks

**Comment by maxcodefaster** [comment]
Oh thank you. I only looked at the readme. My fault sry.
