### ISSUE TITLE
Export Typing

### ISSUE THREAD

**Issue by maxcodefaster** [TanglePay/TanglePay-SDK#28]
To use this esm module in a typescript project it needs types:

https://stackoverflow.com/questions/41292559/could-not-find-a-declaration-file-for-module-module-name-path-to-module-nam

Use case:

I want to import this library in my angular app, but I cant as it has no typings.

**Comment by alexmengyuan** [comment]
Hi max,
We will add types ASAP,
Thx for the catch

**Comment by alexmengyuan** [comment]
Hi max,
v0.0.9 has just been released, index.d.ts is added there,
let me know if this solves your problem.
Thx

**Comment by maxcodefaster** [comment]
Mhm maybe i am importing it wrong but:

<img width="943" alt="image" src="https://user-images.githubusercontent.com/35369883/227495191-5fd69c5f-7179-479b-a099-db29cd98a1c3.png">

<img width="373" alt="image" src="https://user-images.githubusercontent.com/35369883/227495243-b2936a01-10c1-4937-99b2-5c23f2115be1.png">

**Comment by alexmengyuan** [comment]
Hi max,
could you try this code snippet to see if it works for you?
import * as iota from 'tanglepay-sdk'
currently the whole package is export default as an object
Thx

**Comment by maxcodefaster** [comment]
> Hi max, could you try this code snippet to see if it works for you? import * as iota from 'tanglepay-sdk' currently the whole package is export default as an object Thx

Same result. Tried this before. I guess it is missing a d.ts file. 


<img width="873" alt="image" src="https://user-images.githubusercontent.com/35369883/227914525-b6f59f85-0977-44c1-90d2-a342eb1f0992.png">

**Comment by alexmengyuan** [comment]
Hi max,
sorry for the inconvenience, 
v0.1.1 is out and I checked index.d.ts in npm page's code tab
let me know if it solves your problem this time
Thx

**Comment by maxcodefaster** [comment]
> Hi max, sorry for the inconvenience, v0.1.1 is out and I checked index.d.ts in npm page's code tab let me know if it solves your problem this time Thx

Yes works! Awesome, thank you :)

<img width="523" alt="image" src="https://user-images.githubusercontent.com/35369883/228163926-0d8a0df1-0e5e-4795-9047-ab6d4a8b9c94.png">

<img width="796" alt="image" src="https://user-images.githubusercontent.com/35369883/228164004-09f97128-5c93-4226-9609-62f1fb7d067c.png">
